### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by seoh** [seoh/reama#3]
- [ ] make `/public` to submodule of [seoh.github.io](/seoh/seoh.github.io) or build-automation
- [ ] submit button
- [ ] make sure of validations

**Comment by seoh** [comment]
- [ ] GFM or CommonMark rendering
